apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "emby.fullname" . }}
  namespace: {{ .Values.service.namespace | default "default" }}
  labels:
    {{- include "emby.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "emby.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "emby.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
        allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            runAsUser: {{ .Values.securityContext.runAsUser }}
            runAsGroup: {{ .Values.securityContext.runAsGroup }}
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- range .Values.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}

      volumes:
        - name: emby-config
        {{- if .Values.persistence.config.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.config.enabled }}
            claimName: {{ .Values.persistence.config.existingClaim }}
            {{- else }}
            claimName: {{ template "emby.fullname" . }}-config
            {{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}

        - name: emby-media
        {{- if .Values.persistence.media.enabled }}
          persistentVolumeClaim:
            {{- if .Values.persistence.media.enabled }}
            claimName: {{ .Values.persistence.media.existingClaim }}
            {{- else }}
            claimName: {{ template "emby.fullname" . }}-media
            {{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
