{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bitcoin.fullname" . }}-ingress
  namespace: {{ .Values.service.namespace | default "default" }}
  labels:
    {{- include "bitcoin.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  ingress:
  - from:
    {{- range .Values.networkPolicy.allowedSubnets }}
    - ipBlock:
      cidr: {{ . }}
    {{- end }}
    ports:
    - protocol: TCP
      port: {{ .Values.service.rpc.port }}
  - ports:
    - protocol: TCP
      port: {{ .Values.service.p2p.port }}
{{- end }}
